apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: dev
data:
  logstash.conf: |
    input {
      tcp {
        port => 5000
        codec => json
      }
    }

    filter {
      if [record] {
        mutate {
          add_field => {
            "file_name" => "%{[record][file][name]}"
            "function_name" => "%{[record][function]}"
            "log_level" => "%{[record][level][name]}"
            "log_message" => "%{[record][message]}"
            "timestamp" => "%{[record][time][repr]}"
          }
        }
      }

      date {
        match => ["timestamp", "yyyy-MM-dd HH:mm:ss.SSSSSS"]
        target => "@timestamp"
        remove_field => ["timestamp"]
      }
    }

    output {
      elasticsearch {
        hosts => ["${ELASTICSEARCH_HOST}"]
        index => "logstash-dev"
      }
      stdout { codec => rubydebug }
    }


# deployment addition
volumeMounts:
      - name: logstash-config-volume
        mountPath: /usr/share/logstash/pipeline/logstash.conf
        subPath: logstash.conf

volumes:
  - name: logstash-config-volume
    configMap:
      name: logstash-config