alg_image_name: beam-manager:latest
api_token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjhTRUJKUmtqNnJfX0dSVENpa2J5RVpqSk1uY1dqNlNMM0JpQWZlR1dJRE0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLXF3Mmp6Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJkYWQyZGZhMi03MjdkLTQ1ODktOTY0Ni1jZjBiYjcxOWEyYjUiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.RYjuuJwE_hKLiHfiemoQdJ6QJUjCVDf-fbhHDcIoxj3lLDzpYgVdONA70on3sFXbZYFU6Olaw3zZasTHeNqw2MQY-pSlE8OmoV-1fjUZHt5hZ8y077u0dMUvmAo1817DOa62GKqqRL7pcNyjrNzXMd5PXOKMUutc_Sq9HeLYVZxkrNeXEra4kjjGTvDG9PRv1I-9GssnbvdYOYpqaF885Yi28vcdO5XG0QL8RZCZxbhxHnKa8I-o2jIBC7Mk8kmdLLUVSp4I4AoOuJ_ZjTtys2Z4PPKwk-KbJfjr4Dr8QyPPpqHmL_-CaqV3AIvxoCfyMzQgkZQEvl_J9NtCXoZIBg
api_url: https://api.kh-dev.dt.local:6443
base_image: harbor.dt.local/public/ubunto_slim:python-3-10
base_url: tcp://10.0.7.55:2375
# client = docker.APIClient(base_url='unix://var/run/docker.sock')
# client = docker.APIClient(base_url='tcp://10.0.7.55:2375')
# client = docker.APIClient(base_url='unix:///home/beam/.docker/run/docker.sock')
# client = docker.APIClient(base_url='unix:////home/beam/runtime/docker.sock')
beam_version: null
body: 'Here is the cluster information:'
check_project_exists: true
command:
  arguments:
  executable:
#  arguments:
#  - -c
#  - /workspace/bash-run-scripts/entrypoint.sh --no-ray #TODO: check if can specify only arguments without executable
#  executable: /bin/bash
requirements_blacklist:
- 'torch'
- 'optuna'
cpu_limits: '2'
cpu_requests: '2'
create_service_account: true
deployment_name: beam-manager
#enable_ray_ports: true
entrypoint_args:
- '--no-ray'
entrypoint_envs:
  TEST: test
from_email: dayotech2018@gmail.com
from_email_password: mkhdokjqwwmazyrf
job_name: beam-job
cron_job_name: beam-cron-job
container_name: beam-cron-container
job_schedule: "*/2 * * * *" # every 2 minutes
gpu_limits: '1'
gpu_requests: '1'
# image_name: harbor.dt.local/public/fake-alg-http-server:latest
#image_name: None
image_name: harbor.dt.local/public/ubunto_slim:python-3-10
#image_name: rocker/rstudio:latest
labels:
  app: beam-manager
memory_limits: '4'
memory_requests: '4'
memory_storage_configs:
- enabled: true
  mount_path: /dev/shm
  name: dshm
  size_gb: 8
#new_image: harbor.dt.local/public/fake-alg-http-server:test1
new_image:  rocker/rstudio:latest
n_pods: '1'
node_selector:
  gpu-type: tesla-a100
project_name: dev
path_to_state: /tmp
# push_image: false - this is removed
#ray_ports_configs:
#- ray_ports:
#  - 6379
#  - 8265
registry_password: Har@123
registry_url: harbor.dt.local
registry_username: admin
registry_project_name: public
replicas: '1'
restart_policy_configs:
#  condition: OnFailure
  condition: Always
  delay: 5s
  active_deadline_seconds: 300
  max_attempts: 3
  window: 120s
send_mail: false
#scc_name: anyuid
scc_name: privileged
security_context_config:
  add_capabilities:
#  - SYS_CHROOT
#  - CAP_AUDIT_CONTROL
#  - CAP_AUDIT_WRITE
  enable_security_context: true
  privileged: true
  runAsUser: 0
service_configs:
- create_ingress: false
  create_route: false
  ingress_host: ssh.example.com
  port: 22022
  port_name: ssh-port
  service_name: ssh
  service_type: NodePort
- create_ingress: false
  create_route: true
  ingress_host: jupyter.example.com
  port: 22088
  port_name: jupyter-port
  service_name: jupyter
  service_type: ClusterIP
- create_ingress: false
  create_route: true
  ingress_host: api.example.com
  port: 35000
  port_name: port
  service_name: api
  service_type: ClusterIP
smtp_port: 587
smtp_server: smtp.gmail.com
storage_configs:
- create_pvc: false
  pvc_access_mode: ReadWriteMany
  pvc_mount_path: /pvc
  pvc_name: data-pvc
  pvc_size: '500'
subject: Cluster Deployment Information
to_email: yossi@dayo-tech.com
use_gpu: false
use_node_selector: false
use_scc: true
user_idm_configs:
- create_role_binding: false
  project_name: ben-guryon
  role_binding_name: yos
  role_name: admin
  user_name: yos
