# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import beam_grpc_pb2 as beam__grpc__pb2


class BeamServiceStub(object):
    """The Beam service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetVariable = channel.unary_unary(
                '/beam.BeamService/SetVariable',
                request_serializer=beam__grpc__pb2.SetVariableRequest.SerializeToString,
                response_deserializer=beam__grpc__pb2.SetVariableResponse.FromString,
                )
        self.GetVariable = channel.unary_unary(
                '/beam.BeamService/GetVariable',
                request_serializer=beam__grpc__pb2.GetVariableRequest.SerializeToString,
                response_deserializer=beam__grpc__pb2.GetVariableResponse.FromString,
                )
        self.QueryAlgorithm = channel.unary_unary(
                '/beam.BeamService/QueryAlgorithm',
                request_serializer=beam__grpc__pb2.QueryAlgorithmRequest.SerializeToString,
                response_deserializer=beam__grpc__pb2.QueryAlgorithmResponse.FromString,
                )


class BeamServiceServicer(object):
    """The Beam service definition.
    """

    def SetVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryAlgorithm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BeamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVariable,
                    request_deserializer=beam__grpc__pb2.SetVariableRequest.FromString,
                    response_serializer=beam__grpc__pb2.SetVariableResponse.SerializeToString,
            ),
            'GetVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVariable,
                    request_deserializer=beam__grpc__pb2.GetVariableRequest.FromString,
                    response_serializer=beam__grpc__pb2.GetVariableResponse.SerializeToString,
            ),
            'QueryAlgorithm': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryAlgorithm,
                    request_deserializer=beam__grpc__pb2.QueryAlgorithmRequest.FromString,
                    response_serializer=beam__grpc__pb2.QueryAlgorithmResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'beam.BeamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BeamService(object):
    """The Beam service definition.
    """

    @staticmethod
    def SetVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/beam.BeamService/SetVariable',
            beam__grpc__pb2.SetVariableRequest.SerializeToString,
            beam__grpc__pb2.SetVariableResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/beam.BeamService/GetVariable',
            beam__grpc__pb2.GetVariableRequest.SerializeToString,
            beam__grpc__pb2.GetVariableResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryAlgorithm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/beam.BeamService/QueryAlgorithm',
            beam__grpc__pb2.QueryAlgorithmRequest.SerializeToString,
            beam__grpc__pb2.QueryAlgorithmResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
