preprocess_body: false
preprocess_title: false
split_dataset: false
build_dataset: false
calc_tfidf: false
calc_dense: false
build_features: false
reload_state: true
save_state: false
tokenizer: intfloat/multilingual-e5-base
# dense-model: intfloat/multilingual-e5-base
#dense-model: beam-http://localhost:29950
#root_path: /home/mlspeech/elads/data/enron/data/
#path_to_data: /home/mlspeech/elads/data/enron/data/emails.parquet
#model_state_path: /home/mlspeech/elads/data/enron/models/model_state_subset
dense-model: beam-http://localhost:31155
path_to_data: /home/hackathon_2023/data/enron/emails_dd.parquet
#model_state_path: /home/shared/data/results/enron/models/model_state_20240625
model_state_path: /home/shared/data/results/enron/models/model_state_20240625_subset
root_path: /home/shared/data/results/enron/dataset_20240606
subset-labels: [36,]

