
'''

TODO: this example will automatically commit and push to git the ci/cd pipeline. It includes:
    the configuration file
    the auto generated .gitlab-ci.yml file

    The autogenerated .gitlab-ci.yml should do the following:
    1. copy the cicd_runner.py file to the base_image
    2. copy the configuration file to the base image

    the cicd_runner.py file must be generic and not associated with any specific project
    the configuration file should be associated with a specific project but its location in the base image should be predefined
    the configuration file should include the path to the manager


'''
