name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: ["main", "doc"]  # Runs on pushes to the 'dev' branch
  workflow_dispatch:  # Allows manual triggering from GitHub Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Ensure this matches your project requirements

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter-book sphinx  # Install both Jupyter Book and Sphinx

      - name: Install dependencies and package
        run: |
          pip install sphinx-autobuild pydata-sphinx-theme
          pip install .  # Install your package and its dependencies from setup.cfg

      - name: Build Jupyter Book
        run: |
          cd book
          jupyter-book build .
          mkdir -p ${{ github.workspace }}/site/book
          cp -r _build/html/* ${{ github.workspace }}/site/book/

      - name: Build Sphinx Documentation
        run: |
          cd docs  # Adjust to your Sphinx docs path
          sphinx-build -b html . ${{ github.workspace }}/site/api

      - name: Add Landing Page
        run: |
          cp index.html ${{ github.workspace }}/site/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'  # Uploads the entire 'site' directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
